package com.example.uapp.thr;

/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.18.1)", date = "2023-05-23")
public class DetailInfo implements org.apache.thrift.TBase<DetailInfo, DetailInfo._Fields>, java.io.Serializable, Cloneable, Comparable<DetailInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DetailInfo");

  private static final org.apache.thrift.protocol.TField ITEM_IMAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("item_image", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new DetailInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new DetailInfoTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer item_image; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ITEM_IMAGE((short)1, "item_image");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ITEM_IMAGE
          return ITEM_IMAGE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ITEM_IMAGE, new org.apache.thrift.meta_data.FieldMetaData("item_image", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DetailInfo.class, metaDataMap);
  }

  public DetailInfo() {
  }

  public DetailInfo(
    java.nio.ByteBuffer item_image)
  {
    this();
    this.item_image = org.apache.thrift.TBaseHelper.copyBinary(item_image);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DetailInfo(DetailInfo other) {
    if (other.isSetItem_image()) {
      this.item_image = org.apache.thrift.TBaseHelper.copyBinary(other.item_image);
    }
  }

  @Override
  public DetailInfo deepCopy() {
    return new DetailInfo(this);
  }

  @Override
  public void clear() {
    this.item_image = null;
  }

  public byte[] getItem_image() {
    setItem_image(org.apache.thrift.TBaseHelper.rightSize(item_image));
    return item_image == null ? null : item_image.array();
  }

  public java.nio.ByteBuffer bufferForItem_image() {
    return org.apache.thrift.TBaseHelper.copyBinary(item_image);
  }

  public DetailInfo setItem_image(byte[] item_image) {
    this.item_image = item_image == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(item_image.clone());
    return this;
  }

  public DetailInfo setItem_image(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer item_image) {
    this.item_image = org.apache.thrift.TBaseHelper.copyBinary(item_image);
    return this;
  }

  public void unsetItem_image() {
    this.item_image = null;
  }

  /** Returns true if field item_image is set (has been assigned a value) and false otherwise */
  public boolean isSetItem_image() {
    return this.item_image != null;
  }

  public void setItem_imageIsSet(boolean value) {
    if (!value) {
      this.item_image = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
    switch (field) {
    case ITEM_IMAGE:
      if (value == null) {
        unsetItem_image();
      } else {
        if (value instanceof byte[]) {
          setItem_image((byte[])value);
        } else {
          setItem_image((java.nio.ByteBuffer)value);
        }
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ITEM_IMAGE:
      return getItem_image();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ITEM_IMAGE:
      return isSetItem_image();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that instanceof DetailInfo)
      return this.equals((DetailInfo)that);
    return false;
  }

  public boolean equals(DetailInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_item_image = true && this.isSetItem_image();
    boolean that_present_item_image = true && that.isSetItem_image();
    if (this_present_item_image || that_present_item_image) {
      if (!(this_present_item_image && that_present_item_image))
        return false;
      if (!this.item_image.equals(that.item_image))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetItem_image()) ? 131071 : 524287);
    if (isSetItem_image())
      hashCode = hashCode * 8191 + item_image.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(DetailInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.compare(isSetItem_image(), other.isSetItem_image());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetItem_image()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.item_image, other.item_image);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DetailInfo(");
    boolean first = true;

    sb.append("item_image:");
    if (this.item_image == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.item_image, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DetailInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DetailInfoStandardScheme getScheme() {
      return new DetailInfoStandardScheme();
    }
  }

  private static class DetailInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<DetailInfo> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, DetailInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ITEM_IMAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.item_image = iprot.readBinary();
              struct.setItem_imageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, DetailInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.item_image != null) {
        oprot.writeFieldBegin(ITEM_IMAGE_FIELD_DESC);
        oprot.writeBinary(struct.item_image);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DetailInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DetailInfoTupleScheme getScheme() {
      return new DetailInfoTupleScheme();
    }
  }

  private static class DetailInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<DetailInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DetailInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetItem_image()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetItem_image()) {
        oprot.writeBinary(struct.item_image);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DetailInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.item_image = iprot.readBinary();
        struct.setItem_imageIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

