username = 'root'
password = '20160137k'
database = 'uapp'
sql_script = r'C:\Users\Administrator\Desktop\Userver\udata\script.sql'
mysql_exec_path = r'C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe'