CREATE DATABASE IF NOT EXISTS UAPP CHARACTER SET utf8;

USE UAPP;

CREATE TABLE IF NOT EXISTS User (
  StudentID VARCHAR(10) NOT NULL PRIMARY KEY,
  Username VARCHAR(20) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Password VARCHAR(20) NOT NULL,
  RegisterTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Item (
  ItemID INT PRIMARY KEY AUTO_INCREMENT,
  ItemTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ItemType VARCHAR(30),
  ItemImgPath VARCHAR(255),
  ItemLocation VARCHAR(255) NOT NULL,
  ItemDescription VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Post (
  PostID INT PRIMARY KEY AUTO_INCREMENT,
  StudentID VARCHAR(10) NOT NULL,
  ItemID INT NOT NULL,
  IsForLost BOOL DEFAULT TRUE,
  PostTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PostContent VARCHAR(255) NOT NULL,
  FOREIGN KEY (StudentID) REFERENCES User(StudentID),
  FOREIGN KEY (ItemID) REFERENCES Item(ItemID)
);

CREATE TABLE IF NOT EXISTS Reply (
  ReplyID INT PRIMARY KEY AUTO_INCREMENT,
  PostID INT NOT NULL,
  StudentID VARCHAR(10) NOT NULL,
  ReplyTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ReplyContent VARCHAR(255) NOT NULL,
  FOREIGN KEY (PostID) REFERENCES Post(PostID),
  FOREIGN KEY (StudentID) REFERENCES User(StudentID)
);








